<a href="https://colab.research.google.com/github/Nsujatno/the-great-winter-lock-in/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch fundamentals and Tensors

FINISHED!!! aprox time: ~ 4 hrs

In [55]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## Intro to tensors

Creating tensors

What is a tensor?
- tensors are multi dimensional arrays with attributes that define their data type, device allocation, and memory layout

In [56]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [57]:
scalar.ndim

0

In [58]:
# get tensor back as python int
scalar.item()

7

In [59]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [60]:
vector.ndim

1

you can tell the number of dimensions a tensor in pytorch has by the num of square brackets

In [61]:
# shape of the tensor
vector.shape

torch.Size([2])

It is size 2 because we have 2 elements inside the square brackets

In [62]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [63]:
MATRIX.ndim

2

In [64]:
MATRIX[0]

tensor([7, 8])

In [65]:
MATRIX[1]

tensor([ 9, 10])

In [66]:
MATRIX.shape

torch.Size([2, 2])

- indexes of the matrix correspond with the rows of it
- the shape is 2x2

In [67]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [68]:
# 3 square brackets so 3 dimensions
TENSOR.ndim

3

In [69]:
# 3x3 shape so shape of [1, 3, 3]
TENSOR.shape

torch.Size([1, 3, 3])

In [70]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [71]:
# so i just tried TENSOR[1] and it didnt work... why? i think bc its 1 3x3 so this should work
TENSOR[0][0]

tensor([1, 2, 3])

In [72]:
TENSOR[0][0][0]

tensor(1)

# Random tensors

why random tensors?
- bc neural networks learn start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [73]:
# Create a random tensor of size or shape (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3444, 0.9941, 0.8115, 0.1249],
        [0.0330, 0.9084, 0.3886, 0.8393],
        [0.9454, 0.1458, 0.7199, 0.6507]])

In [74]:
random_tensor.ndim

2

In [75]:
random_tensor.shape

torch.Size([3, 4])

In [76]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [77]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [80]:
ones.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [81]:
# use torch.arange(start, end, step)
one_to_ten = torch.arange(1, 11, 2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [82]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# tensor datatypes

Tensor datatypes is one of the 3 big issues with PyTorch and deep learning:
1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device

In [83]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # wether to use cpu or gpu
                               requires_grad=False) # if you want pytorch to track gradient when it goes through calculations
float_32_tensor

tensor([3., 6., 9.])

In [84]:
float_32_tensor.dtype

torch.float32

In [85]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

Sometimes when pytorch creates tensors for you, you want to get more info about them to debug

In [86]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6710, 0.1234, 0.2346, 0.8191],
        [0.9582, 0.1307, 0.5750, 0.6180],
        [0.3402, 0.2303, 0.9404, 0.7442]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors (tensor operations)

- addition
- subtraction
- multiplication
- division
- matrix multiplication

In [87]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [88]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [89]:
# tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [90]:
# subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [91]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

# Matrix multiplication

uses `torch.matmul()` method
2 main rules for matrix multiplication:


1.   The inner dimensins must match
2.   The resulting matrix has the shape of the outer dimensions



In [92]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [93]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [94]:
# matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [95]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix mul work by transposing the tensor.
- `torch.transpose(input, dim0, dim1)` - where input is hte desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped
- `tensor.T` - where tensor is the desired tensor to transpose

In [97]:
# tensor a and b
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [98]:
# tensor and and b transposed
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [99]:
# now matrix mult should work
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"output shape: {output.shape}")

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (tensor aggregation)

In [100]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [101]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [102]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [103]:
# find the mean, needs to be float datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [104]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Positional min/max
want to find what index min/max is at

In [105]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [106]:
# find the position in tensor that has the minimum value with argmin
x.argmin()

tensor(0)

In [107]:
x[0]

tensor(0)

In [108]:
# max
x.argmax()

tensor(9)

In [109]:
x[9]

tensor(90)

# Reshaping, stacking, squeezing, and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other or side by side
- Squeeze - removes all 1 dimensions from a tensor
- Unsqueeze - add a 1 dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted in a certain way

In [110]:
# create tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [111]:
# add extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [112]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [113]:
# changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [114]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [115]:
# Stack tensors side by side
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [116]:
# squeeze and unsqueeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [117]:
# torch.unsqueeze()
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(0)
print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [118]:
# torch.permute rearranges the dimensions in a specified order
x_original = torch.rand(size=(244, 244, 3)) # height width color channels

# permute the original tensor to rearrange the axis or dim
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1-> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


# Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy

In [119]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [120]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [121]:
# index on the middle bracket (dim 1)
x[0][0]

tensor([1, 2, 3])

In [122]:
# lets index on the most inner bracket (last dim)
x[0][0][0]

tensor(1)

In [123]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [124]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [125]:
# get all values of the 0 dimension but only 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [126]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [127]:
# index on x to return 9
print(x[0][2][2])

# index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


# Pytorch tensors and numpy

Numpy is very populat so pytorch has functionality to interact with it

- Data in numpy, what in pytorch tensor -> `torch.from_numpy(ndarray)`
- Pytorch tensor -> numpy -> torch.Tensor.numpy()

In [128]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [129]:
array.dtype

dtype('float64')

In [130]:
torch.arange(1.0, 8.0).dtype

torch.float32

# Reproducibility (trying to take random out of random)

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**

In [131]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0352, 0.6865, 0.0875, 0.9950],
        [0.7997, 0.5185, 0.7159, 0.8223],
        [0.8825, 0.3317, 0.9928, 0.2482]])
tensor([[0.8655, 0.6167, 0.1614, 0.6626],
        [0.1891, 0.3780, 0.3839, 0.8264],
        [0.7349, 0.9841, 0.1261, 0.4465]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [132]:
# lets make random but reproducible tensors
import torch

# set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and pytorch objects on gpus

In [133]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [134]:
# check for gpu access with pytorch
import torch
torch.cuda.is_available()

False

In [135]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [136]:
# count number of devices
torch.cuda.device_count()

0

# Putting tensors and models on gpu

gpus are faster at computations

In [137]:
# create a tensor (default on the cpu)
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [138]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [139]:
# move tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Finished up Pytorch fundamentals
approx time: ~ 4 hrs

# Exercises

In [140]:
# Create a random tensor with shape (7, 7)
import torch
x = torch.rand(7,7)
x, x.shape

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]),
 torch.Size([7, 7]))

In [141]:
# Perform a matrix multiplication on the tensor
# from 2 with another random tensor with shape (1, 7)
y = torch.rand(1, 7)
output = torch.mm(x, y.T)
output

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [142]:
# Set the random seed to 0 and do
# exercises 2 & 3 over again.
torch.manual_seed(0)
x = torch.rand(7, 7)
torch.manual_seed(0)
y = torch.rand(1, 7)
output = torch.mm(x, y.T)
x, y, y.T, output

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[0.4963],
         [0.7682],
         [0.0885],
         [0.1320],
         [0.3074],
         [0.6341],
         [0.4901]]),
 tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]))

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [1]:
import torch
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).


In [3]:
torch.manual_seed(1234)
x = torch.rand(2,3)
torch.manual_seed(1234)
y = torch.rand(2,3)
x, y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [5]:
output = torch.mm(x, y.T)
output

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

8. Find the maximum and minimum values of the output of 7.


In [6]:
torch.min(output)

tensor(0.2161)

In [7]:
torch.max(output)

tensor(0.6287)

9. Find the maximum and minimum index values of the output of 7.

In [10]:
torch.argmin(output)

tensor(1)

In [11]:
torch.argmax(output)

tensor(3)

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [15]:
torch.manual_seed(7)
rand = torch.rand(1, 1, 1, 10)
rand, rand.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [16]:
rand.squeeze(), rand.squeeze().shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))